# Generated by Django 4.2.4 on 2024-09-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_auth', '0002_emailcode_remove_smsmessage_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsmessage',
            options={'verbose_name': 'Email log', 'verbose_name_plural': 'Email logs'},
        ),
    ]
