# Generated by Django 4.2.4 on 2024-07-22 18:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('text', models.CharField(max_length=300, verbose_name='text')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('next_id', models.CharField(max_length=50, verbose_name='id')),
                ('conditions', models.CharField(max_length=300, verbose_name='conditions')),
                ('type', models.CharField(choices=[('SINGLE ', 'Single'), ('MULTI - NQ ONE', 'MULTI - NQ ONE'), ('CUSTOM', 'Custom'), ('MULTI - NQ EACH', 'MULTI - NQ EACH')], default='SINGLE ', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions_queue', models.CharField(max_length=1000, verbose_name='Questions queue')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.CharField(max_length=1000, verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder_form.answer', verbose_name='answer_id')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder_form.project', verbose_name='project_id')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder_form.question', verbose_name='question_id'),
        ),
    ]
