# Generated by Django 4.2.4 on 2024-08-05 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='answer_text',
            field=models.CharField(default='', max_length=300, verbose_name='answer_text'),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=300, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='text_template',
            field=models.CharField(default='', max_length=1000, verbose_name='text_template'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='conditions',
            field=models.TextField(max_length=10000, verbose_name='conditions'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='type',
            field=models.CharField(choices=[('SINGLE ', 'Single'), ('MULTI - NQ ONE', 'MULTI - NQ ONE'), ('CUSTOM', 'Custom'), ('MULTI - NQ EACH', 'MULTI - NQ EACH'), ('NUMBER EACH', 'NUMBER EACH')], default='SINGLE ', max_length=300),
        ),
        migrations.CreateModel(
            name='QuestionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.CharField(max_length=10000, verbose_name='params')),
                ('text', models.CharField(max_length=1000, verbose_name='text_template')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder_form.question', verbose_name='parent_question')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder_form.project', verbose_name='project_id')),
            ],
        ),
    ]
