# Generated by Django 4.2.4 on 2024-08-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0002_remove_question_text_answerquestion_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='questions_queue',
            field=models.CharField(default='Q1,', max_length=1000, verbose_name='Questions queue'),
        ),
    ]
