# Generated by Django 4.2.4 on 2024-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0003_alter_project_questions_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='conditions',
            field=models.TextField(default='{"params": "", "conditions":"", "insertion": "Right"}', max_length=10000, verbose_name='conditions'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MULTI - NQ ONE', 'MULTI - NQ ONE'), ('CUSTOM', 'Custom'), ('MULTI - NQ EACH', 'MULTI - NQ EACH'), ('NUMBER EACH', 'NUMBER EACH')], default='SINGLE', max_length=300),
        ),
        migrations.AlterField(
            model_name='questioninstance',
            name='params',
            field=models.CharField(default='{"data":[]}', max_length=10000, verbose_name='params'),
        ),
        migrations.AlterField(
            model_name='questioninstance',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='text'),
        ),
    ]
