# Generated by Django 4.2.4 on 2024-08-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0004_alter_answer_conditions_alter_answer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninstance',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
