# Generated by Django 4.2.4 on 2024-08-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0005_alter_questioninstance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninstance',
            name='qid',
            field=models.CharField(default='', max_length=50, verbose_name='question_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questioninstance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
