# Generated by Django 4.2.4 on 2024-08-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0007_project_created_project_last_edit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termin', models.CharField(max_length=300, verbose_name='Termin')),
                ('desription', models.CharField(max_length=1000, verbose_name='Description')),
                ('qid', models.CharField(max_length=50, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_edit',
            field=models.DateTimeField(blank=True, verbose_name='last_edit'),
        ),
    ]
