# Generated by Django 4.2.4 on 2024-08-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0009_rename_desription_termin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='history_queue',
            field=models.CharField(blank=True, default='', max_length=10000, verbose_name='History queue'),
        ),
        migrations.AlterField(
            model_name='project',
            name='questions_queue',
            field=models.CharField(blank=True, default='', max_length=10000, verbose_name='Questions queue'),
        ),
    ]
