# Generated by Django 4.2.4 on 2024-09-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0013_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestion',
            name='question_instance',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='builder_form.questioninstance', verbose_name='Question Instance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questioninstance',
            name='parent_pk',
            field=models.CharField(default='', max_length=50, verbose_name='parent_pk'),
        ),
    ]
