# Generated by Django 4.2.4 on 2024-09-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0014_answerquestion_question_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='question_instance',
            field=models.PositiveIntegerField(default='', max_length=50, verbose_name='question_instance'),
        ),
        migrations.AlterField(
            model_name='questioninstance',
            name='parent_pk',
            field=models.PositiveIntegerField(default='', max_length=50, verbose_name='parent_pk'),
        ),
    ]
