# Generated by Django 4.2.4 on 2024-10-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0015_alter_answerquestion_question_instance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamingCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('EQUAL', 'Equal'), ('NOT_EQUAL', 'Not Equal'), ('GREATER_THAN', 'Greater Than'), ('LESS_THAN', 'Less Than'), ('IN', 'In'), ('NOT_IN', 'Not In'), ('CONTAINS', 'Contains'), ('NOT_CONTAINS', 'Not Contains'), ('ANSWERED', 'Answered'), ('NOT_ANSWERED', 'Not Answered')], max_length=20, verbose_name='Condition Type')),
                ('left_operand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_operand', to='builder_form.question', verbose_name='Question Answers')),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_question', to='builder_form.question', verbose_name='Parent Question')),
                ('right_operand', models.ManyToManyField(blank=True, to='builder_form.answer', verbose_name='Answers')),
            ],
        ),
    ]
