# Generated by Django 4.2.4 on 2024-10-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0017_namingcondition_text_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninstance',
            name='context',
            field=models.JSONField(default=dict, verbose_name='context'),
        ),
        migrations.AlterField(
            model_name='namingcondition',
            name='condition_type',
            field=models.CharField(choices=[('EQUAL', 'Equal'), ('NOT_EQUAL', 'Not Equal')], max_length=50, verbose_name='Condition Type'),
        ),
    ]
