# Generated by Django 4.2.4 on 2024-11-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0018_questioninstance_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(default=10, verbose_name='Cost of one purchase')),
                ('tests_per_purchase', models.PositiveBigIntegerField(default=1, verbose_name='Tests per one purchase')),
                ('isActive', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
        ),
    ]
