# Generated by Django 4.2.4 on 2024-11-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0019_appsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='tests_per_purchase',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='projects_per_purchase',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Projects per one purchase'),
        ),
    ]
