# Generated by Django 4.2.4 on 2024-11-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0020_remove_appsettings_tests_per_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninstance',
            name='number_id',
            field=models.PositiveIntegerField(default=0, verbose_name='question is in project'),
        ),
    ]
