# Generated by Django 4.2.4 on 2024-12-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0021_questioninstance_number_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='answered_questions',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Answered questions'),
        ),
    ]
