# Generated by Django 4.2.4 on 2024-12-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0022_project_answered_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninstance',
            name='parent_answek_pl',
            field=models.PositiveIntegerField(default=0, max_length=50, verbose_name='parent_answer_pk'),
        ),
        migrations.AlterField(
            model_name='questioninstance',
            name='parent_pk',
            field=models.PositiveIntegerField(default=0, max_length=50, verbose_name='parent_pk'),
        ),
    ]
