# Generated by Django 4.2.4 on 2024-12-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0024_rename_parent_answek_pl_questioninstance_parent_answek_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questioninstance',
            old_name='parent_answek_pk',
            new_name='parent_answer_pk',
        ),
    ]
