# Generated by Django 4.2.4 on 2024-12-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0026_alter_questioninstance_parent_answer_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninstance',
            name='number_id',
        ),
    ]
