# Generated by Django 4.2.4 on 2024-12-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_form', '0027_remove_questioninstance_number_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=10000, verbose_name='Short description'),
        ),
    ]
