# Generated by Django 4.2.4 on 2025-02-05 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('builder_form', '0028_project_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('subject', models.CharField(max_length=255, verbose_name='Header')),
                ('html_content', models.TextField(verbose_name='HTML-code')),
                ('groups', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Groups')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Email mail',
                'verbose_name_plural': 'Email messages',
                'ordering': ['-created'],
            },
        ),
    ]
