# Generated by Django 4.2.4 on 2023-09-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customerinfo_nurseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseinfo',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='nurseinfo',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='nurseinfo',
            name='expirience',
            field=models.PositiveIntegerField(verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Заказчик'), ('nurse', 'Сиделка'), ('admin', 'Администратор'), ('manager', 'Менеджер')], default='customer', max_length=300),
        ),
    ]
