# Generated by Django 4.2.4 on 2023-10-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customerinfo_options_alter_nurseinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linked_card',
            field=models.BooleanField(default=False, verbose_name='Привязана ли карта'),
        ),
    ]
