# Generated by Django 4.2.4 on 2024-01-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(default='', max_length=300, verbose_name='ID в телеграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=300, verbose_name='Токен в cloudpayments для оплаты'),
        ),
    ]
