# Generated by Django 4.2.4 on 2024-01-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_telegram_id_alter_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='user',
            name='chat_telegram_id',
            field=models.CharField(default='', max_length=300, verbose_name='ID чата с user в телеграм'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(default='', max_length=300, verbose_name='Username в телеграм'),
        ),
    ]
