# Generated by Django 4.2.4 on 2024-02-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_user_telegram_id_user_chat_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_mask',
            field=models.CharField(default='', max_length=300, verbose_name='Маска карты оплаты'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_type',
            field=models.CharField(default='', max_length=300, verbose_name='Тип карты'),
        ),
    ]
