# Generated by Django 4.2.4 on 2024-09-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_card_mask_user_card_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
        migrations.DeleteModel(
            name='NurseInfo',
        ),
    ]
