# Generated by Django 4.2.4 on 2024-09-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_nurseinfo_user_delete_customerinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_mask',
        ),
        migrations.RemoveField(
            model_name='user',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chat_telegram_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linked_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=50, verbose_name='phone_number'),
            preserve_default=False,
        ),
    ]
