# Generated by Django 4.2.4 on 2024-11-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_user_card_mask_remove_user_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tests_availables',
            field=models.PositiveIntegerField(default=0, verbose_name='Availables tests'),
        ),
        migrations.AddField(
            model_name='user',
            name='tests_creates',
            field=models.PositiveIntegerField(default=0, verbose_name='Created tests'),
        ),
    ]
