# Generated by Django 4.2.4 on 2024-11-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_tests_availables_user_tests_creates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tests_availables',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tests_creates',
        ),
        migrations.AddField(
            model_name='user',
            name='projects_availables',
            field=models.PositiveIntegerField(default=0, verbose_name='Availables projects'),
        ),
        migrations.AddField(
            model_name='user',
            name='projects_creates',
            field=models.PositiveIntegerField(default=0, verbose_name='Created projects'),
        ),
    ]
