# Generated by Django 4.2.4 on 2024-11-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_user_tests_availables_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='projects_creates',
            new_name='projects_created',
        ),
    ]
