# Generated by Django 4.2.4 on 2024-11-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_projects_creates_user_projects_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='projects_availables',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projects_created',
        ),
    ]
