# Generated by Django 4.2.4 on 2023-09-16 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('care_type', models.CharField(choices=[('several_house', 'На несколько часов в день'), ('with_accommodation', 'C проживанием')], default='several_house', max_length=300, verbose_name='На какое время нужна сиделка?')),
                ('time_start', models.CharField(default='', max_length=300, verbose_name='Когда сиделка должна приступить к работе?')),
                ('contact_type', models.CharField(default='', max_length=300, verbose_name='Как с вами связаться?')),
                ('in_archive', models.BooleanField(default=False, verbose_name='В архив')),
                ('bitrix_id', models.IntegerField(default=-1, verbose_name='ID в bitrix')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='NurseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('address', models.CharField(max_length=300, verbose_name='Адрес клиента')),
                ('comment', models.TextField(default='', verbose_name='комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('in_archive', models.BooleanField(default=False, verbose_name='В архив')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость за посещение')),
                ('care_type', models.CharField(choices=[('several_house', 'На несколько часов в день'), ('with_accommodation', 'C проживанием')], default='several_house', max_length=300, verbose_name='На какое время нужна сиделка?')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_orders', to='grace.nurseapplication', to_field='uuid', verbose_name='Заявка')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Клиент')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_orders', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Cиделка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('balance', models.FloatField(default=0.0, verbose_name='Баланс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='TransferPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_commission', models.BooleanField(default=False, verbose_name='Фиксированная комиссия')),
                ('fixed_rate', models.IntegerField(default=100, verbose_name='Фиксированная ставка')),
                ('percent_rate', models.IntegerField(default=10, verbose_name='Процентная ставка')),
                ('root_wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grace.wallet', verbose_name='Корневой кошелек')),
            ],
            options={
                'verbose_name': 'Настройка прибыли',
                'verbose_name_plural': 'Настройки прибыли',
            },
        ),
        migrations.CreateModel(
            name='NurseVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(verbose_name='Дата визита')),
                ('time', models.TimeField(verbose_name='Время визита')),
                ('completed', models.BooleanField(default=False, verbose_name='Посещение выполнено')),
                ('nursecomment', models.TextField(default='', verbose_name='Комментарий сиделки')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Время Создания')),
                ('completed_date', models.DateTimeField(default=None, verbose_name='Время Создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='grace.nurseorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
        migrations.CreateModel(
            name='NurseAppelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('comment', models.TextField(verbose_name='Причина жалобы')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Удовлетворена'), ('pending', 'На рассмотрении'), ('canceled', 'Отменена')], default='new', max_length=50, verbose_name='Статус')),
                ('ans', models.TextField(verbose_name='Ответ администратора')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appelations', to='grace.nursevisit', to_field='uuid', verbose_name='Посещение')),
            ],
            options={
                'verbose_name': 'Аппеляция визита',
                'verbose_name_plural': 'Аппеляции визитов',
            },
        ),
    ]
