# Generated by Django 4.2.4 on 2023-09-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0002_remove_nurseappelation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurseappelation',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='nurseapplication',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='nurseorder',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='nursevisit',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='uuid',
            new_name='id',
        ),
    ]
