# Generated by Django 4.2.4 on 2023-09-16 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0003_rename_uuid_nurseappelation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseorder',
            name='application',
            field=models.OneToOneField(default='05e7b914-803d-49f0-9fc0-19b7b1203e00', on_delete=django.db.models.deletion.CASCADE, related_name='application_orders', to='grace.nurseapplication', verbose_name='Заявка'),
            preserve_default=False,
        ),
    ]
