# Generated by Django 4.2.4 on 2023-09-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0004_nurseorder_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursevisit',
            name='order',
            field=models.ForeignKey(default='106c443e-00d2-414f-baeb-7804cb30ff61', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='grace.nurseorder', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
