# Generated by Django 4.2.4 on 2023-09-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0006_nurseappelation_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseorder',
            name='client',
        ),
    ]
