# Generated by Django 4.2.4 on 2023-09-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0008_remove_nurseapplication_in_archive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseapplication',
            name='care_type',
            field=models.CharField(choices=[('several_hours', 'На несколько часов в день'), ('with_accommodation', 'C проживанием')], default='several_hours', max_length=300, verbose_name='На какое время нужна сиделка?'),
        ),
        migrations.AlterField(
            model_name='nurseorder',
            name='care_type',
            field=models.CharField(choices=[('several_hours', 'На несколько часов в день'), ('with_accommodation', 'C проживанием')], default='several_hours', max_length=300, verbose_name='На какое время нужна сиделка?'),
        ),
    ]
