# Generated by Django 4.2.4 on 2023-09-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0009_alter_nurseapplication_care_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseorder',
            name='a',
            field=models.CharField(default='dd', max_length=50, verbose_name='jdj'),
            preserve_default=False,
        ),
    ]
