# Generated by Django 4.2.4 on 2023-09-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0010_nurseorder_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseorder',
            name='a',
        ),
    ]
