# Generated by Django 4.2.4 on 2023-09-16 21:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0011_remove_nurseorder_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseorder',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=25), blank=True, default=['a'], size=7, verbose_name='Дни посещения'),
            preserve_default=False,
        ),
    ]
