# Generated by Django 4.2.4 on 2023-09-17 14:39

from django.db import migrations, models
import grace.choices


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0012_nurseorder_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseorder',
            name='in_archive',
        ),
        migrations.RemoveField(
            model_name='nurseorder',
            name='is_active',
        ),
        migrations.AddField(
            model_name='nurseorder',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание оплаты'), ('active', 'Активный'), ('in archive', 'В архиве')], default='waiting', max_length=50, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='nurseorder',
            name='days',
            field=grace.choices.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=25), blank=True, size=7, verbose_name='Дни посещения'),
        ),
    ]
