# Generated by Django 4.2.4 on 2023-09-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0014_alter_nurseorder_days_visitday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseorder',
            name='days',
        ),
    ]
