# Generated by Django 4.2.4 on 2023-10-09 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0016_alter_nurseapplication_care_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursevisit',
            name='completed_date',
            field=models.DateTimeField(default=datetime.date(2000, 1, 1), verbose_name='Время выполнения'),
        ),
    ]
