# Generated by Django 4.2.4 on 2023-10-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0017_alter_nursevisit_completed_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name="wallet",
        ),
        
        migrations.AlterField(
            model_name='nurseorder',
            name='status',
            field=models.CharField(choices=[('Ожидание оплаты', 'Ожидание оплаты'), ('Тестовый период', 'Тестовый период'), ('Активный', 'Активный'), ('В архиве', 'В архиве')], default='Ожидание оплаты', max_length=50, verbose_name='Статус заказа'),
        ),
        # migrations.RemoveField(
        #     model_name='wallet',
        #     name='id',
        # ),
    ]
