# Generated by Django 4.2.4 on 2023-10-17 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grace', '0019_alter_wallet_options_wallet_balance_wallet_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseorder',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_orders', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Сиделка'),
        ),
        migrations.AlterField(
            model_name='nursevisit',
            name='nursecomment',
            field=models.TextField(default='нет', verbose_name='Комментарий сиделки'),
        ),
    ]
