# Generated by Django 4.2.4 on 2023-10-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0020_alter_nurseorder_nurse_alter_nursevisit_nursecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
