# Generated by Django 4.2.4 on 2023-10-19 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0021_alter_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitday',
            name='time',
        ),
        migrations.AddField(
            model_name='visitday',
            name='time_end',
            field=models.TimeField(default=datetime.time(13, 0), verbose_name='Время конца посещения'),
        ),
        migrations.AddField(
            model_name='visitday',
            name='time_start',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Время начала посещения'),
        ),
    ]
