# Generated by Django 4.2.4 on 2023-11-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0025_alter_nurseappelation_ans_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseappelation',
            name='status',
            field=models.CharField(choices=[('Новая', 'Новая'), ('Удовлетворена', 'Удовлетворена'), ('На рассмотрении', 'На рассмотрении'), ('Отменена', 'Отменена')], default='Новая', max_length=50, verbose_name='Статус'),
        ),
    ]
