# Generated by Django 4.2.4 on 2024-01-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0026_alter_nurseappelation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accumulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default='', max_length=300)),
                ('amount', models.IntegerField(default=0)),
                ('сreatedDateIso', models.CharField(default='', max_length=300)),
                ('token', models.CharField(default='', max_length=300)),
                ('escrowAccumulationId', models.CharField(default='', max_length=300)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accumalations', to='grace.nurseorder', verbose_name='Безопасная сделка')),
            ],
            options={
                'verbose_name': 'Безопасная сделка',
                'verbose_name_plural': 'Безопасные сделки',
            },
        ),
    ]
