# Generated by Django 4.2.4 on 2024-02-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0028_alter_nurseorder_care_type_alter_nurseorder_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseorder',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
