# Generated by Django 4.2.4 on 2024-02-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0029_nurseorder_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseorder',
            name='order_number',
            field=models.IntegerField(default=1),
        ),
    ]
