# Generated by Django 4.2.4 on 2024-02-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0030_alter_nurseorder_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseorder',
            name='order_number',
            field=models.IntegerField(default=1, verbose_name='Номер'),
        ),
    ]
