# Generated by Django 4.2.4 on 2024-03-20 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0031_alter_nurseorder_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='Сумма начисления сиделке')),
                ('accumulatuion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grace.accumulation', verbose_name='Безопасная сделка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grace.nurseorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
            },
        ),
    ]
