# Generated by Django 4.2.4 on 2024-03-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grace', '0032_createnursepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createnursepayment',
            old_name='accumulatuion',
            new_name='accumulation',
        ),
    ]
